### PR TITLE
Rudimentary separation between configuration and integration

### PR DESCRIPTION
**Pull request by JulianKniephoff**
This splits the configuration file into actual configuration, and "integrations" (i.e. functions and settings that configure how Annotate communicates with Opencast, or if it uses `localStorage`).

The latter is not really configuration in the sense that an adopter is not supposed to change them in their build; they are rather part of the code.

I'm not too happy with the way this code is placed and loaded, etc., but at least it is independent of the configuration now, so we can move it around in the future.

### CODE REVIEW

**Comment by JulianKniephoff** [comment]
Merge conflict is fixed. :D

**Comment by rrolf** [comment]
This version does not load if I deploy it to Opencast

**Comment by rrolf** [comment]
require.js:33 GET http://rolf.virtuos.uos.de:8080/annotation-tool/js/annotation-tool-configuration.js net::ERR_ABORTED 404 (Not Found)

**Comment by Arnei** [comment]
Builds, but won't load when deployed to Opencast (Version 8.3). 

Console errors:
```
Uncaught TypeError: comparators[i] is not a function
    at util.js:178
```
```
Uncaught Error: Can't create config, layout not yet initialised
    at lm.LayoutManager.toConfig (goldenlayout.js:582)
```

**Comment by JulianKniephoff** [comment]
Should be fixed. :)

**Review by Arnei — APPROVED** [review]
Now loads and works in Opencast 8.3
